version: '3'

services:
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"

  airflow:
    image: apache/airflow:2.6.0
    container_name: airflow
    ports:
      - "8081:8080"
